# Generated by Django 4.2.30 on 2026-05-24 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cantiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cliente', models.CharField(blank=True, max_length=200)),
                ('indirizzo', models.CharField(blank=True, max_length=300)),
                ('stato', models.CharField(choices=[('attivo', 'Attivo'), ('sospeso', 'Sospeso'), ('concluso', 'Concluso')], default='attivo', max_length=20)),
                ('data_inizio', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Cantiere',
                'verbose_name_plural': 'Cantieri',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Dipendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('ruolo', models.CharField(choices=[('operaio', 'Operaio'), ('caposquadra', 'Caposquadra'), ('tecnico', 'Tecnico'), ('subappaltatore', 'Subappaltatore')], default='operaio', max_length=50)),
                ('costo_orario', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Costo orario (€/h)')),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dipendente',
                'verbose_name_plural': 'Dipendenti',
                'ordering': ['cognome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='GiornataDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('n_operai', models.PositiveSmallIntegerField(default=1, verbose_name='N. operai presenti')),
                ('ore_lavorate', models.DecimalField(decimal_places=1, default=8.0, max_digits=4, verbose_name='Ore lavorate (per operaio)')),
                ('desc_preventivo', models.TextField(blank=True, help_text='Descrivi liberamente le lavorazioni eseguite previste dal preventivo.', verbose_name='Attività di preventivo')),
                ('desc_extra', models.TextField(blank=True, help_text='Descrivi le attività extra non previste dal preventivo.', verbose_name='Attività extra')),
                ('desc_materiali', models.TextField(blank=True, help_text='Descrivi i materiali ricevuti, ritirati o utilizzati oggi.', verbose_name='Bolle materiale')),
                ('ai_processata', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cantiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giornate', to='core.cantiere')),
            ],
            options={
                'verbose_name': 'Giornata',
                'verbose_name_plural': 'Giornate',
                'ordering': ['-data', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClusterAttivita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.CharField(choices=[('preventivo', 'Preventivo'), ('extra', 'Extra'), ('materiali', 'Materiali')], max_length=20)),
                ('categoria', models.CharField(choices=[('cartongesso', 'Cartongesso'), ('finitura', 'Finitura / Stuccatura'), ('pittura', 'Pittura'), ('resina', 'Resina / Microcemento'), ('extra', 'Extra / Non preventivato'), ('materiali', 'Materiali / Bolle'), ('logistica', 'Logistica'), ('altro', 'Altro')], default='altro', max_length=30)),
                ('descrizione', models.TextField()),
                ('ore_stimate', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('giornata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='core.giornatadiario')),
            ],
            options={
                'verbose_name': 'Cluster attività',
                'verbose_name_plural': 'Cluster attività',
                'ordering': ['categoria'],
            },
        ),
    ]
