# Generated by Django 4.2.30 on 2026-05-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegolaKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200, unique=True)),
                ('categoria', models.CharField(choices=[('cartongesso', 'Cartongesso'), ('finitura', 'Finitura / Stuccatura'), ('pittura', 'Pittura'), ('resina', 'Resina / Microcemento'), ('extra', 'Extra / Non preventivato'), ('materiali', 'Materiali / Bolle'), ('logistica', 'Logistica'), ('altro', 'Altro')], max_length=30)),
            ],
            options={
                'verbose_name': 'Regola keyword',
                'verbose_name_plural': 'Regole keyword',
                'ordering': ['categoria', 'keyword'],
            },
        ),
    ]
