# Generated by Django 4.2.30 on 2026-05-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_regolakeyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaLavorazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Identificatore breve senza spazi (es. posa-pavimenti)', unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('tema', models.CharField(choices=[('blu', 'Blu'), ('verde', 'Verde'), ('giallo', 'Giallo'), ('viola', 'Viola'), ('rosso', 'Rosso'), ('arancio', 'Arancio'), ('grigio', 'Grigio'), ('teal', 'Teal'), ('rosa', 'Rosa')], default='grigio', max_length=20)),
                ('keywords', models.TextField(blank=True, help_text='Una keyword per riga. Usata per classificare automaticamente le attività.')),
                ('ordine', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoria lavorazione',
                'verbose_name_plural': 'Categorie lavorazioni',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.AlterField(
            model_name='clusterattivita',
            name='categoria',
            field=models.CharField(default='altro', max_length=50),
        ),
        migrations.AlterField(
            model_name='regolakeyword',
            name='categoria',
            field=models.CharField(max_length=50),
        ),
    ]
