# Generated by Django 4.2.30 on 2026-05-25 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_categorie_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterattivita',
            name='avanzamento',
            field=models.CharField(blank=True, choices=[('iniziato', 'Iniziato'), ('in_corso', 'In corso'), ('completato', 'Completato')], max_length=20),
        ),
        migrations.AddField(
            model_name='clusterattivita',
            name='dipendenti_nomi',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cantiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambienti', to='core.cantiere')),
            ],
            options={
                'verbose_name': 'Ambiente',
                'verbose_name_plural': 'Ambienti',
                'ordering': ['nome'],
                'unique_together': {('cantiere', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='clusterattivita',
            name='ambiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clusters', to='core.ambiente'),
        ),
    ]
