# Generated by Django 4.2.30 on 2026-05-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_clusterattivita_avanzamento_and_more'),
    ]

    operations = [
        migrations.DeleteModel(name='RegolaKeyword'),
    ]
