# Generated by Django 4.2.30 on 2026-05-25 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_regolakeyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giornatadiario',
            name='n_operai',
        ),
        migrations.RemoveField(
            model_name='giornatadiario',
            name='ore_lavorate',
        ),
    ]
